"""
backend/app/services/gemini_explainer.py

Grounded Gemini AI Diagnostics & Root Cause Reasoning Service for FactoryMind AI.

Consumes structured evidence with verified data source transparency and data quality,
invokes Google Gemini with strict system instructions preventing hallucinations,
validates structured JSON outputs, and provides a deterministic evidence-grounded fallback.
"""

import asyncio
import json
import logging
import re
from typing import Dict, List, Optional, Any
from pydantic import BaseModel, Field, ValidationError

from backend.app.config import settings

logger = logging.getLogger("factorymind.gemini")

# Grounded System Instruction
GROUNDED_SYSTEM_PROMPT = """You are the FactoryMind Industrial Diagnostic Copilot, an expert turbofan engine prognostic reasoning assistant.

YOUR MISSION:
Explain the machine's current operational risk state to an industrial plant operator using ONLY the provided structured evidence payload.

GROUNDING & INTEGRITY RULES (ZERO TOLERANCE FOR HALLUCINATIONS):
1. Use ONLY facts directly stated in the provided JSON evidence payload.
2. NEVER invent sensor measurements, operational limits, or baseline values.
3. NEVER invent machine maintenance history, flight logs, or prior repair events.
4. Clearly distinguish:
   - Data Source Context (e.g. NASA C-MAPSS Simulation vs Real Industrial Telemetry)
   - Data Quality (e.g. GOOD vs STALE vs WARNING)
   - Observed Telemetry (e.g. sensor readings, z-scores, delta deviations)
   - ML Model Predictions (RUL, anomaly score, composite health index)
   - AI Reasoning & Recommended Actions
5. If telemetry data is marked as STALE, state clearly that data is stale and distinguish sensor connectivity lag from machine mechanical breakdown.
6. If ML compatibility is INCOMPATIBLE or predictions are unavailable, state clearly that RUL cannot be predicted due to missing sensor channels.
7. NEVER promise an exact calendar date or guaranteed moment of breakdown; represent the RUL as an ML model estimate with uncertainty.
8. Output MUST be valid JSON adhering strictly to the requested schema.
"""


class GeminiDiagnosticReport(BaseModel):
    summary: str = Field(description="High-level 1-2 sentence executive diagnostic summary")
    risk_explanation: str = Field(description="Clear explanation of why the engine is in the current risk state based on model outputs and sensor deviations")
    evidence: List[str] = Field(description="Bullet points of verified sensor measurements, z-scores, and physical trends supporting the diagnosis")
    recommended_action: str = Field(description="One practical, actionable, industrial maintenance recommendation or inspection procedure")
    confidence: str = Field(description="Confidence rating: High, Medium, or Low")
    limitations: str = Field(description="Engineering boundaries and assumptions of the diagnosis")
    source: str = Field(default="gemini", description="Source of the diagnostic report: 'gemini' or 'fallback'")
    is_fallback: bool = Field(default=False, description="Whether this report was generated by the deterministic fallback engine")
    model_used: str = Field(default="gemini-2.0-flash", description="AI model or fallback identifier")


def generate_deterministic_fallback(evidence: Dict[str, Any], reason: str = "Gemini API unavailable") -> GeminiDiagnosticReport:
    """
    Generates a 100% grounded, deterministic diagnostic report directly from the structured evidence.
    Used when GEMINI_API_KEY is not set, rate limits are hit, or network is unavailable.
    """
    unit_id = evidence.get("unit_number", 1)
    cycle = evidence.get("current_cycle", 1)
    rul = evidence.get("rul_prediction_cycles", 100.0)
    health = evidence.get("health_index_percent", 100.0)
    risk_level = evidence.get("risk_level", "NORMAL")
    anomaly_status = evidence.get("anomaly_status", "NORMAL")
    signals = evidence.get("contributing_signals", [])
    data_source = evidence.get("data_source", {})
    source_name = data_source.get("source_name", "NASA C-MAPSS FD001")
    is_sim = data_source.get("is_simulation", True)
    data_quality = evidence.get("data_quality", "GOOD")
    is_stale = evidence.get("is_stale", False)
    ml_compat = evidence.get("ml_compatibility", {})
    is_predictable = ml_compat.get("is_rul_predictable", True)

    # Extract top sensor deviations
    evidence_points = []
    top_subsystems = set()
    for s in signals[:4]:
        name = s.get("name", s.get("sensor_id"))
        subsys = s.get("subsystem", "Turbofan Core")
        delta = s.get("delta", 0.0)
        z = s.get("z_score", 0.0)
        direction = s.get("trend_direction", "stable")
        units = s.get("units", "")
        top_subsystems.add(subsys)
        evidence_points.append(
            f"{name} ({subsys}): observed delta of {delta:+.2f} {units} (z-score: {z:+.2f}, trend: {direction})."
        )

    if not evidence_points:
        evidence_points.append("All monitored sensor channels are operating within nominal baseline bounds.")

    # Data Quality Note
    if is_stale:
        evidence_points.append("Telemetry feed status: STALE (last observation timestamp exceeds active threshold).")
    else:
        evidence_points.append(f"Data Quality: {data_quality} (Source: {source_name}).")

    primary_subsys = list(top_subsystems)[0] if top_subsystems else "High Pressure Compressor (HPC)"

    if not is_predictable:
        summary = f"Machine #{unit_id:03d} telemetry received via {source_name}. Prognostic RUL is unavailable due to incomplete sensor schema."
        explanation = f"Incoming telemetry schema does not match the 21-channel feature schema required by the C-MAPSS ML models. Model predictions have been withheld to avoid fabricated outputs."
        recommendation = "Map required sensor channels in Settings -> Data Sources to enable automated RUL prognostics."
        confidence = "High"
    elif is_stale:
        summary = f"Turbofan Unit #{unit_id:03d} data stream is STALE at cycle {cycle}. Last known Health Index was {health:.1f}%."
        explanation = f"Sensor communication is delayed. Machine health cannot be confirmed in real time. Stale telemetry does not automatically indicate machine failure."
        recommendation = "Verify IoT gateway / network connectivity and inspect sensor transmission logs."
        confidence = "Medium"
    elif risk_level == "CRITICAL":
        summary = f"Turbofan Unit #{unit_id:03d} has reached CRITICAL risk at cycle {cycle}. Estimated Remaining Useful Life is {rul:.1f} cycles with Health Index at {health:.1f}%."
        explanation = (
            f"Multi-cycle degradation persistence detected severe drift primarily affecting {primary_subsys}. "
            f"Isolation Forest flagged operational status as {anomaly_status} with significant thermodynamic deviations."
        )
        recommendation = f"Issue immediate priority work order for borescope inspection on {primary_subsys} and prepare replacement line module."
        confidence = "High"
    elif risk_level == "WARNING":
        summary = f"Turbofan Unit #{unit_id:03d} exhibits accelerated degradation (WARNING) at cycle {cycle}. Estimated RUL is {rul:.1f} cycles (Health Index: {health:.1f}%)."
        explanation = (
            f"The engine shows consistent sensor divergence in {primary_subsys}. "
            f"Predictive RUL indicates accelerated degradation requiring scheduling within the next {int(rul)} cycles."
        )
        recommendation = f"Schedule scheduled maintenance inspection for {primary_subsys} stator vanes and verify bleed air valves."
        confidence = "High"
    elif risk_level == "MONITOR":
        summary = f"Turbofan Unit #{unit_id:03d} is under MONITOR state at cycle {cycle}. Health Index is {health:.1f}% with estimated RUL of {rul:.1f} cycles."
        explanation = f"Minor sensor drift observed in {primary_subsys}. Operational metrics remain within serviceable limits with low immediate failure risk."
        recommendation = "Continue telemetry monitoring at current sample frequency; log baseline drift on next scheduled turnaround."
        confidence = "Medium"
    else:
        summary = f"Turbofan Unit #{unit_id:03d} is operating in NORMAL healthy condition at cycle {cycle} (Health Index: {health:.1f}%)."
        explanation = "All key turbofan core temperatures, pressures, and rotor speeds are tracking historical healthy baselines with minimal anomaly scores."
        recommendation = "No maintenance required. Maintain standard operational procedures."
        confidence = "High"

    mode_str = "Simulation" if is_sim else "Real Factory Telemetry"
    return GeminiDiagnosticReport(
        summary=summary,
        risk_explanation=explanation,
        evidence=evidence_points,
        recommended_action=recommendation,
        confidence=confidence,
        limitations=f"Generated by deterministic rules engine ({reason}). Strictly grounded on {mode_str} telemetry evidence ({source_name}).",
        source="fallback",
        is_fallback=True,
        model_used="deterministic-rules-engine-v1.0"
    )


def extract_json_from_text(text: str) -> Dict[str, Any]:
    """Extracts and parses JSON from raw LLM output strings, handling markdown codeblocks."""
    cleaned = text.strip()
    if cleaned.startswith("```"):
        # Remove code fence
        lines = cleaned.split("\n")
        if lines[0].startswith("```"):
            lines = lines[1:]
        if lines and lines[-1].startswith("```"):
            lines = lines[:-1]
        cleaned = "\n".join(lines).strip()

    # Regex search for JSON object if needed
    match = re.search(r"\{.*\}", cleaned, re.DOTALL)
    if match:
        return json.loads(match.group(0))
    return json.loads(cleaned)


async def generate_gemini_diagnosis(evidence: Dict[str, Any]) -> GeminiDiagnosticReport:
    """
    Calls Google Gemini API with structured evidence payload and returns validated diagnostic report.
    Automatically falls back to deterministic engine on network error, invalid JSON, or missing API key.
    """
    api_key = settings.GEMINI_API_KEY
    model_name = settings.effective_gemini_model

    if not api_key or "your-gemini-api-key" in api_key or not api_key.startswith("AIzaSy"):
        logger.info("Valid GEMINI_API_KEY (AIzaSy...) not detected. Utilizing deterministic evidence fallback.")
        return generate_deterministic_fallback(evidence, reason="Deterministic Rules Engine Active")

    prompt = f"""EVIDENCE PAYLOAD (Engine Telemetry, Data Quality & ML Prognostics):
```json
{json.dumps(evidence, indent=2)}
```

INSTRUCTIONS:
Analyze the provided evidence payload and return a strictly grounded diagnostic report formatted as valid JSON matching this exact structure:
{{
  "summary": "<Concise 1-2 sentence diagnostic summary>",
  "risk_explanation": "<Detailed explanation of the risk level based strictly on the evidence, distinguishing observed data from ML models>",
  "evidence": [
    "<Specific observed sensor delta with units, z-score, and trend>",
    "<Second specific sensor observation from the payload>",
    "<Data quality and source transparency note>"
  ],
  "recommended_action": "<One specific, practical maintenance or inspection action>",
  "confidence": "High",
  "limitations": "<Engineering constraints and assumption note stating data source and ML compatibility>"
}}
"""

    def _invoke_sync_gemini():
        try:
            from google import genai
            client = genai.Client(api_key=api_key)
            response = client.models.generate_content(
                model=model_name,
                contents=prompt,
                config={
                    "system_instruction": GROUNDED_SYSTEM_PROMPT,
                    "response_mime_type": "application/json",
                    "temperature": 0.1,
                    "http_options": {"timeout": 2000}
                }
            )
            return response.text
        except Exception as genai_err:
            raise RuntimeError(f"GenAI SDK error: {genai_err}")

    try:
        raw_text = await asyncio.wait_for(
            asyncio.to_thread(_invoke_sync_gemini),
            timeout=1.5
        )

        # Parse JSON and validate with Pydantic
        parsed_json = extract_json_from_text(raw_text)
        report = GeminiDiagnosticReport(
            summary=parsed_json.get("summary", ""),
            risk_explanation=parsed_json.get("risk_explanation", ""),
            evidence=parsed_json.get("evidence", []),
            recommended_action=parsed_json.get("recommended_action", ""),
            confidence=parsed_json.get("confidence", "High"),
            limitations=parsed_json.get("limitations", "Grounded strictly on verified telemetry evidence."),
            source="gemini",
            is_fallback=False,
            model_used=model_name
        )
        logger.info(f"Gemini diagnostic generated successfully using model: {model_name}")
        return report

    except Exception as e:
        logger.error(f"Gemini diagnostic generation error: {e}. Switching to deterministic fallback.")
        return generate_deterministic_fallback(evidence, reason=f"Gemini API Error: {str(e)[:100]}")
